services:
  api:
    build: 
      context: .
      # Especificar el archivo Dockerfile si tuviera otro nombre
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    depends_on:
      db:
        condition: service_healthy # Espera a que la DB esté lista, no solo iniciada

  db:
    image: postgres:15-alpine # 'alpine' es mucho más ligera y segura
    environment:
      POSTGRES_USER: ${DB_USER:-invoice_user} # Permite usar variables de entorno
      POSTGRES_PASSWORD: ${DB_PASS:-invoice_pass}
      POSTGRES_DB: ${DB_NAME:-invoices}
    healthcheck: # Añadimos esto para que la API sepa CUÁNDO conectar
      test: ["CMD-SHELL", "pg_isready -U invoice_user -d invoices"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: